// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAmnxFsdZ8jeTeW2VBvj2jKJkm6m3zDQ',
    appId: '1:70897694595:web:0b0f7176d709b23723e8b6',
    messagingSenderId: '70897694595',
    projectId: 'cloneapptiktok-4c440',
    authDomain: 'cloneapptiktok-4c440.firebaseapp.com',
    storageBucket: 'cloneapptiktok-4c440.appspot.com',
    measurementId: 'G-C393SWSE9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhc3QrmJg9jhM62wP0WFtzrmiDK0iP4X8',
    appId: '1:70897694595:android:85ed05e2583569e823e8b6',
    messagingSenderId: '70897694595',
    projectId: 'cloneapptiktok-4c440',
    storageBucket: 'cloneapptiktok-4c440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFbdgSJTOnmCP1aem_0nEmwuRfcwF1Qp8',
    appId: '1:70897694595:ios:8130f4bcafdb7a6323e8b6',
    messagingSenderId: '70897694595',
    projectId: 'cloneapptiktok-4c440',
    storageBucket: 'cloneapptiktok-4c440.appspot.com',
    iosClientId: '70897694595-ca75qa7v7lcv3ig90gie2qci2gm7tmt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneTiktok',
  );
}
